"""schema change

Revision ID: 7adc8cc32dbd
Revises: e59da292a594
Create Date: 2024-03-22 13:20:11.719747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7adc8cc32dbd'
down_revision: Union[str, None] = 'e59da292a594'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_review',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_month', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('fiscal_year', sa.String(), nullable=True),
    sa.Column('transport_type', sa.String(), nullable=True),
    sa.Column('line_name', sa.String(), nullable=True),
    sa.Column('section_heading', sa.String(), nullable=True),
    sa.Column('comments', sa.String(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ssle_metro'
    )
    op.create_table('arrest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_month', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('fiscal_year', sa.String(), nullable=True),
    sa.Column('transport_type', sa.String(), nullable=True),
    sa.Column('line_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('ethinicity', sa.String(), nullable=True),
    sa.Column('station_name', sa.String(), nullable=True),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('arrest_count', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ssle_metro'
    )
    op.create_table('arrest_landing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transport_type', sa.String(), nullable=True),
    sa.Column('current_year_month', sa.Date(), nullable=True),
    sa.Column('current_month_count', sa.Integer(), nullable=True),
    sa.Column('current_year_count', sa.Integer(), nullable=True),
    sa.Column('previous_year_count', sa.Integer(), nullable=True),
    sa.Column('previous_year_count_percent', sa.Integer(), nullable=True),
    sa.Column('previous_month_count', sa.Integer(), nullable=True),
    sa.Column('previous_month_count_percent', sa.Integer(), nullable=True),
    sa.Column('admin_review_id', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ssle_metro'
    )
    op.create_table('calls_for_service',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_month', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('fiscal_year', sa.String(), nullable=True),
    sa.Column('transport_type', sa.String(), nullable=True),
    sa.Column('line_name', sa.String(), nullable=True),
    sa.Column('call_type', sa.String(), nullable=True),
    sa.Column('station_name', sa.String(), nullable=True),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('calls_count', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ssle_metro'
    )
    op.create_table('calls_for_service_landing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transport_type', sa.String(), nullable=True),
    sa.Column('current_year_month', sa.Date(), nullable=True),
    sa.Column('current_month_count', sa.Integer(), nullable=True),
    sa.Column('current_year_count', sa.Integer(), nullable=True),
    sa.Column('previous_year_month_count', sa.Integer(), nullable=True),
    sa.Column('previous_year_month_count_percent', sa.Integer(), nullable=True),
    sa.Column('previous_month_count', sa.Integer(), nullable=True),
    sa.Column('previous_month_count_percent', sa.Integer(), nullable=True),
    sa.Column('admin_review_id', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ssle_metro'
    )
    op.create_table('crime_landing',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transport_type', sa.String(), nullable=True),
    sa.Column('current_year_month', sa.Date(), nullable=True),
    sa.Column('current_month_count', sa.Integer(), nullable=True),
    sa.Column('current_year_count', sa.Integer(), nullable=True),
    sa.Column('total_boardings', sa.Integer(), nullable=True),
    sa.Column('crime_per_100k_boardings', sa.Integer(), nullable=True),
    sa.Column('previous_year_count', sa.Integer(), nullable=True),
    sa.Column('previous_year_count_percent', sa.Integer(), nullable=True),
    sa.Column('previous_month_count', sa.Integer(), nullable=True),
    sa.Column('previous_month_count_percent', sa.Integer(), nullable=True),
    sa.Column('admin_review_id', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ssle_metro'
    )
    op.create_table('crime_unvetted',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_month', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('fiscal_year', sa.String(), nullable=True),
    sa.Column('week_no', sa.Integer(), nullable=True),
    sa.Column('from_date', sa.Date(), nullable=True),
    sa.Column('to_date', sa.Date(), nullable=True),
    sa.Column('transport_type', sa.String(), nullable=True),
    sa.Column('line_name', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('ucr', sa.String(), nullable=True),
    sa.Column('crime_name', sa.String(), nullable=True),
    sa.Column('station_name', sa.String(), nullable=True),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('crime_count', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ssle_metro'
    )
    op.create_table('crime_vetted',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year_month', sa.Date(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month', sa.String(), nullable=True),
    sa.Column('fiscal_year', sa.String(), nullable=True),
    sa.Column('transport_type', sa.String(), nullable=True),
    sa.Column('line_name', sa.String(), nullable=True),
    sa.Column('severity', sa.String(), nullable=True),
    sa.Column('ucr', sa.String(), nullable=True),
    sa.Column('crime_name', sa.String(), nullable=True),
    sa.Column('station_name', sa.String(), nullable=True),
    sa.Column('agency_name', sa.String(), nullable=True),
    sa.Column('crime_count', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ssle_metro'
    )
    op.create_table('location',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transport_type', sa.String(), nullable=True),
    sa.Column('station_name', sa.String(), nullable=True),
    sa.Column('line_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ssle_metro'
    )
    op.create_table('riders_summary',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('month_number', sa.Integer(), nullable=True),
    sa.Column('day_type', sa.String(), nullable=True),
    sa.Column('line_name', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('date_count', sa.Integer(), nullable=True),
    sa.Column('avg_daily_riders', sa.Float(), nullable=True),
    sa.Column('avg_daily_pmiles', sa.Float(), nullable=True),
    sa.Column('riders_total', sa.Integer(), nullable=True),
    sa.Column('pmiles_total', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='ssle_metro'
    )
    op.drop_table('admin_review')
    op.drop_table('crime_unvetted')
    op.drop_table('crime_landing')
    op.drop_table('riders_summary')
    op.drop_table('arrest_landing')
    op.drop_table('crime_vetted')
    op.drop_table('calls_for_service')
    op.drop_table('location')
    op.drop_table('calls_for_service_landing')
    op.drop_table('arrest')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arrest',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year_month', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fiscal_year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transport_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('line_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ethinicity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('station_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agency_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('arrest_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='arrest_pkey')
    )
    op.create_table('calls_for_service_landing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transport_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_year_month', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('current_month_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_year_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_year_month_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_year_month_count_percent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_month_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_month_count_percent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('admin_review_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='calls_for_service_landing_pkey')
    )
    op.create_table('location',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transport_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('station_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('line_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='location_pkey')
    )
    op.create_table('calls_for_service',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year_month', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fiscal_year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transport_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('line_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('call_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('station_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agency_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('calls_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='calls_for_service_pkey')
    )
    op.create_table('crime_vetted',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year_month', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fiscal_year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transport_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('line_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ucr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('crime_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('station_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agency_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('crime_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='crime_vetted_pkey')
    )
    op.create_table('arrest_landing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transport_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_year_month', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('current_month_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_year_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_year_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_year_count_percent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_month_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_month_count_percent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('admin_review_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='arrest_landing_pkey')
    )
    op.create_table('riders_summary',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('day_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('line_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('date_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('avg_daily_riders', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('avg_daily_pmiles', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('riders_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('pmiles_total', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='riders_summary_pkey')
    )
    op.create_table('crime_landing',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('transport_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_year_month', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('current_month_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('current_year_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_boardings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('crime_per_100k_boardings', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_year_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_year_count_percent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_month_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('previous_month_count_percent', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('admin_review_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='crime_landing_pkey')
    )
    op.create_table('crime_unvetted',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year_month', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fiscal_year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('week_no', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('from_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('to_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('transport_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('line_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('severity', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ucr', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('crime_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('station_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('agency_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('crime_count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='crime_unvetted_pkey')
    )
    op.create_table('admin_review',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('year_month', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('month', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('fiscal_year', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transport_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('line_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section_heading', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('published', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='admin_review_pkey')
    )
    op.drop_table('riders_summary', schema='ssle_metro')
    op.drop_table('location', schema='ssle_metro')
    op.drop_table('crime_vetted', schema='ssle_metro')
    op.drop_table('crime_unvetted', schema='ssle_metro')
    op.drop_table('crime_landing', schema='ssle_metro')
    op.drop_table('calls_for_service_landing', schema='ssle_metro')
    op.drop_table('calls_for_service', schema='ssle_metro')
    op.drop_table('arrest_landing', schema='ssle_metro')
    op.drop_table('arrest', schema='ssle_metro')
    op.drop_table('admin_review', schema='ssle_metro')
    # ### end Alembic commands ###
